import SwiftUI

// GENERATED by `codeyam-editor editor isolate` — do not edit by hand.
//
// Renders a single component in isolation on the booted simulator, selected by
// the CODEYAM_ISOLATE_COMPONENT / CODEYAM_ISOLATE_SCENARIO env vars (set via a component scenario's
// deviceState.launchEnv, delivered to the app as SIMCTL_CHILD_* on launch).
// Returns nil when no component is selected so the app renders its normal root.
//
// Wire this into your @main App once:
//   WindowGroup { CodeyamIsolationHost.root() ?? AnyView(ContentView()) }
public enum CodeyamIsolationHost {
    public static func root() -> AnyView? {
        let env = ProcessInfo.processInfo.environment
        guard let component = env["CODEYAM_ISOLATE_COMPONENT"] else { return nil }
        let scenario = env["CODEYAM_ISOLATE_SCENARIO"] ?? "Default"
        switch component {
        case "AddCounterDot":
            return AnyView(AddCounterDotIsolated(scenario: scenario))
        case "AppSettingsPanel":
            return AnyView(AppSettingsPanelIsolated(scenario: scenario))
        case "BottomControlRow":
            return AnyView(BottomControlRowIsolated(scenario: scenario))
        case "BoundedScroll":
            return AnyView(BoundedScrollIsolated(scenario: scenario))
        case "ControlButton":
            return AnyView(ControlButtonIsolated(scenario: scenario))
        case "CountHero":
            return AnyView(CountHeroIsolated(scenario: scenario))
        case "CounterBottomBar":
            return AnyView(CounterBottomBarIsolated(scenario: scenario))
        case "CounterColorPicker":
            return AnyView(CounterColorPickerIsolated(scenario: scenario))
        case "CounterDot":
            return AnyView(CounterDotIsolated(scenario: scenario))
        case "CounterGraphChart":
            return AnyView(CounterGraphChartIsolated(scenario: scenario))
        case "CounterGraphView":
            return AnyView(CounterGraphViewIsolated(scenario: scenario))
        case "CounterListPanel":
            return AnyView(CounterListPanelIsolated(scenario: scenario))
        case "CounterSettingsPanel":
            return AnyView(CounterSettingsPanelIsolated(scenario: scenario))
        case "CounterStepStepper":
            return AnyView(CounterStepStepperIsolated(scenario: scenario))
        case "CounterSwitcherCard":
            return AnyView(CounterSwitcherCardIsolated(scenario: scenario))
        case "FeedbackDisclosureToggle":
            return AnyView(FeedbackDisclosureToggleIsolated(scenario: scenario))
        case "GearButton":
            return AnyView(GearButtonIsolated(scenario: scenario))
        case "GraphEventList":
            return AnyView(GraphEventListIsolated(scenario: scenario))
        case "GraphHeader":
            return AnyView(GraphHeaderIsolated(scenario: scenario))
        case "GraphHistorySelector":
            return AnyView(GraphHistorySelectorIsolated(scenario: scenario))
        case "HeaderBar":
            return AnyView(HeaderBarIsolated(scenario: scenario))
        case "IncrementBar":
            return AnyView(IncrementBarIsolated(scenario: scenario))
        case "OverridePicker":
            return AnyView(OverridePickerIsolated(scenario: scenario))
        default:
            return AnyView(Text("Unknown isolated component: \(component)"))
        }
    }
}
